/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package edu.au.cc.gallery.ui;
import edu.au.cc.gallery.data.Postgres;
import edu.au.cc.gallery.data.UserDAO;
import edu.au.cc.gallery.data.User;
import edu.au.cc.gallery.aws.S3;

import static spark.Spark.*;
import spark.Request;
import spark.Response;

import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import java.sql.SQLException;

import spark.ModelAndView;

import spark.template.handlebars.HandlebarsTemplateEngine;

public class App {
    public String getGreeting() {
        return "Hello Christine!";
    }
   private static UserDAO getUserDAO() throws Exception {
   return Postgres.getUserDAO();
  }

    public static void main(String[] args) throws Exception {
       // System.out.println(new App().getGreeting());
	//DB.demo();
	//UserAdmin.interactiveProgram();
    String portString = System.getenv("JETTY_PORT");
	if (portString == null || portString.equals(""))
	    port(5000);
	else
	    port(Integer.parseInt(portString));

      //  User u = getUserDAO().getUserByUsername("fred");
       // System.out.println(u); 
       new userManager().addRoutes();
      new userMain().addRoutes();
   //  S3.demo();
    }
}
